// 模型列表
const modelList = [
  { name: 'Aether', filename: 'Aether.vrm' },
  { name: 'Alhaitham', filename: 'Alhaitham.vrm' },
  { name: 'Amber', filename: 'Amber.vrm' },
  { name: 'Amber2', filename: 'Amber2.vrm' },
  { name: 'Arlecchino', filename: 'Arlecchino.vrm' },
  { name: 'avatar', filename: 'avatar.vrm' },
  { name: 'Baizhu', filename: 'Baizhu.vrm' },
  { name: 'Beidou', filename: 'Beidou.vrm' },
  { name: 'Bennett', filename: 'Bennett.vrm' },
  { name: 'Bronya', filename: 'Bronya.vrm' },
  { name: 'Candace', filename: 'Candace.vrm' },
  { name: 'Chongyun', filename: 'Chongyun.vrm' },
  { name: 'Collei', filename: 'Collei.vrm' },
  { name: 'Dehya', filename: 'Dehya.vrm' },
  { name: 'Diluc', filename: 'Diluc.vrm' },
  { name: 'Dori', filename: 'Dori.vrm' },
  { name: 'Eula', filename: 'Eula.vrm' },
  { name: 'Eula2', filename: 'Eula2.vrm' },
  { name: 'Faruzan', filename: 'Faruzan.vrm' },
  { name: 'Fischl', filename: 'Fischl.vrm' },
  { name: 'Ganyu', filename: 'Ganyu.vrm' },
  { name: 'Gorou', filename: 'Gorou.vrm' },
  { name: 'Himeko', filename: 'Himeko.vrm' },
  { name: 'HuTao', filename: 'HuTao.vrm' },
  { name: 'Jean', filename: 'Jean.vrm' },
  { name: 'Jean2', filename: 'Jean2.vrm' },
  { name: 'Kaedehara Kazuha', filename: 'Kaedehara Kazuha.vrm' },
  { name: 'Kaeya', filename: 'Kaeya.vrm' },
  { name: 'Kamisato Ayaka', filename: 'KamisatoAyaka.vrm' },
  { name: 'Katheryne', filename: 'Katheryne.vrm' },
  { name: 'Kaveh', filename: 'Kaveh.vrm' },
  { name: 'Kazuha', filename: 'Kazuha.vrm' },
  { name: 'Keqing', filename: 'Keqing.vrm' },
  { name: 'Klara', filename: 'Klara.vrm' },
  { name: 'Klee', filename: 'Klee.vrm' },
  { name: 'Kujou Sara', filename: 'KujouSara.vrm' },
  { name: 'Kuki Shinobu', filename: 'KukiShinobu.vrm' },
  { name: 'Layla', filename: 'Layla.vrm' },
  { name: 'Lisa', filename: 'Lisa.vrm' },
  { name: 'lumina', filename: 'lumina.vrm' },
  { name: 'Mika', filename: 'Mika.vrm' },
  { name: 'Mimi', filename: 'Mimi.vrm' },
  { name: 'Mona', filename: 'Mona.vrm' },
  { name: 'Mona2', filename: 'Mona2.vrm' },
  { name: 'Nahida', filename: 'Nahida.vrm' },
  { name: 'Natasha', filename: 'Natasha.vrm' },
  { name: 'Nilou', filename: 'Nilou.vrm' },
  { name: 'Ningguang', filename: 'Ningguang.vrm' },
  { name: 'Ningguang2', filename: 'Ningguang2.vrm' },
  { name: 'Noelle', filename: 'Noelle.vrm' },
  { name: 'Paimon', filename: 'Paimon.vrm' },
  { name: 'Qiqi', filename: 'Qiqi.vrm' },
  { name: 'Qiqi2', filename: 'Qiqi2.vrm' },
  { name: 'Raiden Shogun', filename: 'RaidenShogun.vrm' },
  { name: 'Raiden Shogun2', filename: 'RaidenShogun2.vrm' },
  { name: 'Razor', filename: 'Razor.vrm' },
  { name: 'Rosaria', filename: 'Rosaria.vrm' },
  { name: 'Rosaria2', filename: 'Rosaria2.vrm' },
  { name: 'Sampo', filename: 'Sampo.vrm' },
  { name: 'Sangonomiya Kokomi', filename: 'SangonomiyaKokomi.vrm' },
  { name: 'Sayu', filename: 'Sayu.vrm' },
  { name: 'Scaramouche', filename: 'Scaramouche.vrm' },
  { name: 'Scaramouche2', filename: 'Scaramouche2.vrm' },
  { name: 'Shenhe', filename: 'Shenhe.vrm' },
  { name: 'Shenhe2', filename: 'Shenhe2.vrm' },
  { name: 'Shikanoin Heizou', filename: 'Shikanoin Heizou.vrm' },
  { name: 'Shikanoin Heizou2', filename: 'Shikanoin Heizou2.vrm' },
  { name: 'Signora', filename: 'Signora.vrm' },
  { name: 'Sucrose', filename: 'Sucrose.vrm' },
  { name: 'Tartaglia', filename: 'Tartaglia.vrm' },
  { name: 'Thoma', filename: 'Thoma.vrm' },
  { name: 'Tsaritsa', filename: 'Tsaritsa.vrm' },
  { name: 'Venti', filename: 'Venti.vrm' },
  { name: 'Wanderer', filename: 'Wanderer.vrm' },
  { name: 'Welt', filename: 'Welt.vrm' },
  { name: 'Xiangling', filename: 'Xiangling.vrm' },
  { name: 'Xiao', filename: 'Xiao.vrm' },
  { name: 'xier', filename: 'xier.vrm' },
  { name: 'Xingqiu', filename: 'Xingqiu.vrm' },
  { name: 'Xinyan', filename: 'Xinyan.vrm' },
  { name: 'Yae Miko', filename: 'YaeMiko.vrm' },
  { name: 'Yanfei', filename: 'Yanfei.vrm' },
  { name: 'Yaoyao', filename: 'Yaoyao.vrm' },
  { name: 'Yoimiya', filename: 'Yoimiya.vrm' },
  { name: 'yuki', filename: 'yuki.vrm' },
  { name: 'Zhongli', filename: 'Zhongli.vrm' }
];

export default modelList;