// 模型列表 - 使用英文名
const modelList = [
  // 崩坏星穹铁道角色
  { name: 'Bronya', filename: 'Bronya.vrm', source: 'honkai', avatar: '❄️' },
  { name: 'Dehya', filename: 'Dehya.vrm', source: 'genshin', avatar: '🔥' },
  { name: 'Himeko', filename: 'Himeko.vrm', source: 'honkai', avatar: '☕' },
  { name: 'Katheryne', filename: 'Katheryne.vrm', source: 'genshin', avatar: '🤖' },
  { name: 'Klara', filename: 'Klara.vrm', source: 'honkai', avatar: '🧸' },
  { name: 'Mimi', filename: 'Mimi.vrm', source: 'honkai', avatar: '🐱' },
  { name: 'Natasha', filename: 'Natasha.vrm', source: 'honkai', avatar: '💉' },
  { name: 'Sampo', filename: 'Sampo.vrm', source: 'honkai', avatar: '🎩' },
  { name: 'Seele', filename: 'Seele.vrm', source: 'honkai', avatar: '🦋' },
  { name: 'Welt', filename: 'Welt.vrm', source: 'honkai', avatar: '📚' },

  // 原神角色 - 按字母顺序
  { name: 'Aether', filename: 'Aether.vrm', source: 'genshin', avatar: '⭐' },
  { name: 'Albedo', filename: 'Albedo.vrm', source: 'genshin', avatar: '🎨' },
  { name: 'Albedo2', filename: 'Albedo2.vrm', source: 'genshin', avatar: '🎨' },
  { name: 'Alhaitham', filename: 'Alhaitham.vrm', source: 'genshin', avatar: '📖' },
  { name: 'Amber', filename: 'Amber.vrm', source: 'genshin', avatar: '🔥' },
  { name: 'Amber2', filename: 'Amber2.vrm', source: 'genshin', avatar: '🔥' },
  { name: 'Arataki Itto', filename: 'AratakiItto.vrm', source: 'genshin', avatar: '👹' },
  { name: 'Arlecchino', filename: 'Arlecchino.vrm', source: 'genshin', avatar: '🎭' },
  { name: 'Baizhu', filename: 'Baizhu.vrm', source: 'genshin', avatar: '🐍' },
  { name: 'Barbara', filename: 'Barbara.vrm', source: 'genshin', avatar: '💧' },
  { name: 'Barbara2', filename: 'Barbara2.vrm', source: 'genshin', avatar: '💧' },
  { name: 'Beidou', filename: 'Beidou.vrm', source: 'genshin', avatar: '⚡' },
  { name: 'Beidou2', filename: 'Beidou2.vrm', source: 'genshin', avatar: '⚡' },
  { name: 'Bennett', filename: 'Bennett.vrm', source: 'genshin', avatar: '🔥' },
  { name: 'Bennett2', filename: 'Bennett2.vrm', source: 'genshin', avatar: '🔥' },
  { name: 'Candace', filename: 'Candace.vrm', source: 'genshin', avatar: '💧' },
  { name: 'Celestia', filename: 'Celestia.vrm', source: 'genshin', avatar: '👁️' },
  { name: 'Chongyun', filename: 'Chongyun.vrm', source: 'genshin', avatar: '❄️' },
  { name: 'Chongyun2', filename: 'Chongyun2.vrm', source: 'genshin', avatar: '❄️' },
  { name: 'Collei', filename: 'Collei.vrm', source: 'genshin', avatar: '🌿' },
  { name: 'Dainsleif', filename: 'Dainsleif.vrm', source: 'genshin', avatar: '⭐' },
  { name: 'Dainsleif2', filename: 'Dainsleif2.vrm', source: 'genshin', avatar: '⭐' },
  { name: 'Diluc', filename: 'Diluc.vrm', source: 'genshin', avatar: '🔥' },
  { name: 'Diluc2', filename: 'Diluc2.vrm', source: 'genshin', avatar: '🔥' },
  { name: 'Diona', filename: 'Diona.vrm', source: 'genshin', avatar: '🐱' },
  { name: 'Diona2', filename: 'Diona2.vrm', source: 'genshin', avatar: '🐱' },
  { name: 'Dori', filename: 'Dori.vrm', source: 'genshin', avatar: '💰' },
  { name: 'Dottore', filename: 'Dottore.vrm', source: 'genshin', avatar: '🔬' },
  { name: 'Eula', filename: 'Eula.vrm', source: 'genshin', avatar: '❄️' },
  { name: 'Eula2', filename: 'Eula2.vrm', source: 'genshin', avatar: '❄️' },
  { name: 'Faruzan', filename: 'Faruzan.vrm', source: 'genshin', avatar: '🌀' },
  { name: 'Fischl', filename: 'Fischl.vrm', source: 'genshin', avatar: '⚡' },
  { name: 'Fischl2', filename: 'Fischl2.vrm', source: 'genshin', avatar: '⚡' },
  { name: 'Ganyu', filename: 'Ganyu.vrm', source: 'genshin', avatar: '❄️' },
  { name: 'Ganyu2', filename: 'Ganyu2.vrm', source: 'genshin', avatar: '❄️' },
  { name: 'Gorou', filename: 'Gorou.vrm', source: 'genshin', avatar: '🐕' },
  { name: 'Gorou2', filename: 'Gorou2.vrm', source: 'genshin', avatar: '🐕' },
  { name: 'Hu Tao', filename: 'HuTao.vrm', source: 'genshin', avatar: '👻' },
  { name: 'Jean', filename: 'Jean.vrm', source: 'genshin', avatar: '💨' },
  { name: 'Jean2', filename: 'Jean2.vrm', source: 'genshin', avatar: '💨' },
  { name: 'Kaedehara Kazuha', filename: 'KaedeharaKazuha.vrm', source: 'genshin', avatar: '🍁' },
  { name: 'Kaeya', filename: 'Kaeya.vrm', source: 'genshin', avatar: '❄️' },
  { name: 'Kaeya2', filename: 'Kaeya2.vrm', source: 'genshin', avatar: '❄️' },
  { name: 'Kamisato Ayaka', filename: 'KamisatoAyaka.vrm', source: 'genshin', avatar: '❄️' },
  { name: 'Kamisato Ayaka2', filename: 'KamisatoAyaka2.vrm', source: 'genshin', avatar: '❄️' },
  { name: 'Kamisato Ayato', filename: 'KamisatoAyato.vrm', source: 'genshin', avatar: '💧' },
  { name: 'Kaveh', filename: 'Kaveh.vrm', source: 'genshin', avatar: '🏛️' },
  { name: 'Kazuha', filename: 'Kazuha.vrm', source: 'genshin', avatar: '🍁' },
  { name: 'Keqing', filename: 'Keqing.vrm', source: 'genshin', avatar: '⚡' },
  { name: 'Keqing2', filename: 'Keqing2.vrm', source: 'genshin', avatar: '⚡' },
  { name: 'Klee', filename: 'Klee.vrm', source: 'genshin', avatar: '💣' },
  { name: 'Kujou Sara', filename: 'KujouSara.vrm', source: 'genshin', avatar: '⚡' },
  { name: 'Kujou Sara2', filename: 'KujouSara2.vrm', source: 'genshin', avatar: '⚡' },
  { name: 'Kuki Shinobu', filename: 'KukiShinobu.vrm', source: 'genshin', avatar: '⚡' },
  { name: 'La Signora', filename: 'LaSignora.vrm', source: 'genshin', avatar: '❄️' },
  { name: 'Layla', filename: 'Layla.vrm', source: 'genshin', avatar: '💤' },
  { name: 'Lisa', filename: 'Lisa.vrm', source: 'genshin', avatar: '⚡' },
  { name: 'Lisa2', filename: 'Lisa2.vrm', source: 'genshin', avatar: '⚡' },
  { name: 'Lumine', filename: 'Lumine.vrm', source: 'genshin', avatar: '⭐' },
  { name: 'Lumine2', filename: 'Lumine2.vrm', source: 'genshin', avatar: '⭐' },
  { name: 'Mika', filename: 'Mika.vrm', source: 'genshin', avatar: '❄️' },
  { name: 'Mona', filename: 'Mona.vrm', source: 'genshin', avatar: '💧' },
  { name: 'Mona2', filename: 'Mona2.vrm', source: 'genshin', avatar: '💧' },
  { name: 'Naganohara Yoimiya', filename: 'NaganoharaYoimiya.vrm', source: 'genshin', avatar: '🔥' },
  { name: 'Naganohara Yoimiya2', filename: 'NaganoharaYoimiya2.vrm', source: 'genshin', avatar: '🔥' },
  { name: 'Nahida', filename: 'Nahida.vrm', source: 'genshin', avatar: '🌿' },
  { name: 'Nilou', filename: 'Nilou.vrm', source: 'genshin', avatar: '💧' },
  { name: 'Ningguang', filename: 'Ningguang.vrm', source: 'genshin', avatar: '💎' },
  { name: 'Ningguang2', filename: 'Ningguang2.vrm', source: 'genshin', avatar: '💎' },
  { name: 'Noelle', filename: 'Noelle.vrm', source: 'genshin', avatar: '🛡️' },
  { name: 'Paimon', filename: 'Paimon.vrm', source: 'genshin', avatar: '🍴' },
  { name: 'Qiqi', filename: 'Qiqi.vrm', source: 'genshin', avatar: '❄️' },
  { name: 'Qiqi2', filename: 'Qiqi2.vrm', source: 'genshin', avatar: '❄️' },
  { name: 'Raiden Shogun', filename: 'RaidenShogun.vrm', source: 'genshin', avatar: '⚡' },
  { name: 'Raiden Shogun2', filename: 'RaidenShogun2.vrm', source: 'genshin', avatar: '⚡' },
  { name: 'Razor', filename: 'Razor.vrm', source: 'genshin', avatar: '⚡' },
  { name: 'Razor2', filename: 'Razor2.vrm', source: 'genshin', avatar: '⚡' },
  { name: 'Rosaria', filename: 'Rosaria.vrm', source: 'genshin', avatar: '❄️' },
  { name: 'Rosaria2', filename: 'Rosaria2.vrm', source: 'genshin', avatar: '❄️' },
  { name: 'Sangonomiya Kokomi', filename: 'SangonomiyaKokomi.vrm', source: 'genshin', avatar: '💧' },
  { name: 'Sayu', filename: 'Sayu.vrm', source: 'genshin', avatar: '🍃' },
  { name: 'Sayu2', filename: 'Sayu2.vrm', source: 'genshin', avatar: '🍃' },
  { name: 'Scaramouche', filename: 'Scaramouche.vrm', source: 'genshin', avatar: '🌀' },
  { name: 'Scaramouche2', filename: 'Scaramouche2.vrm', source: 'genshin', avatar: '🌀' },
  { name: 'Shenhe', filename: 'Shenhe.vrm', source: 'genshin', avatar: '❄️' },
  { name: 'Shenhe2', filename: 'Shenhe2.vrm', source: 'genshin', avatar: '❄️' },
  { name: 'Shikanoin Heizou', filename: 'ShikanoinHeizou.vrm', source: 'genshin', avatar: '💨' },
  { name: 'Shikanoin Heizou2', filename: 'ShikanoinHeizou2.vrm', source: 'genshin', avatar: '💨' },
  { name: 'Sucrose', filename: 'Sucrose.vrm', source: 'genshin', avatar: '🌀' },
  { name: 'Tartaglia', filename: 'Tartaglia.vrm', source: 'genshin', avatar: '💧' },
  { name: 'Tartaglia2', filename: 'Tartaglia2.vrm', source: 'genshin', avatar: '💧' },
  { name: 'Thoma', filename: 'Thoma.vrm', source: 'genshin', avatar: '🔥' },
  { name: 'Thoma2', filename: 'Thoma2.vrm', source: 'genshin', avatar: '🔥' },
  { name: 'Tighnari', filename: 'Tighnari.vrm', source: 'genshin', avatar: '🌿' },
  { name: 'Tsaritsa', filename: 'Tsaritsa.vrm', source: 'genshin', avatar: '❄️' },
  { name: 'Venti', filename: 'Venti.vrm', source: 'genshin', avatar: '💨' },
  { name: 'Venti2', filename: 'Venti2.vrm', source: 'genshin', avatar: '💨' },
  { name: 'Venti3', filename: 'Venti3.vrm', source: 'genshin', avatar: '💨' },
  { name: 'Wanderer', filename: 'Wanderer.vrm', source: 'genshin', avatar: '🌀' },
  { name: 'Xiangling', filename: 'Xiangling.vrm', source: 'genshin', avatar: '🔥' },
  { name: 'Xiangling2', filename: 'Xiangling2.vrm', source: 'genshin', avatar: '🔥' },
  { name: 'Xiao', filename: 'Xiao.vrm', source: 'genshin', avatar: '👹' },
  { name: 'Xiao2', filename: 'Xiao2.vrm', source: 'genshin', avatar: '👹' },
  { name: 'Xingqiu', filename: 'Xingqiu.vrm', source: 'genshin', avatar: '💧' },
  { name: 'Xingqiu2', filename: 'Xingqiu2.vrm', source: 'genshin', avatar: '💧' },
  { name: 'Xinyan', filename: 'Xinyan.vrm', source: 'genshin', avatar: '🔥' },
  { name: 'Xinyan2', filename: 'Xinyan2.vrm', source: 'genshin', avatar: '🔥' },
  { name: 'Yae Miko', filename: 'YaeMiko.vrm', source: 'genshin', avatar: '⚡' },
  { name: 'Yae Miko Alt', filename: 'YaeMikoAlt.vrm', source: 'genshin', avatar: '⚡' },
  { name: 'Yanfei', filename: 'Yanfei.vrm', source: 'genshin', avatar: '🔥' },
  { name: 'Yanfei2', filename: 'Yanfei2.vrm', source: 'genshin', avatar: '🔥' },
  { name: 'Yaoyao', filename: 'Yaoyao.vrm', source: 'genshin', avatar: '🌿' },
  { name: 'Yelan', filename: 'Yelan.vrm', source: 'genshin', avatar: '💧' },
  { name: 'Yoimiya', filename: 'Yoimiya.vrm', source: 'genshin', avatar: '🔥' },
  { name: 'Yun Jin', filename: 'YunJin.vrm', source: 'genshin', avatar: '🎭' },
  { name: 'Yun Jin2', filename: 'YunJin2.vrm', source: 'genshin', avatar: '🎭' },
  { name: 'Zhongli', filename: 'Zhongli.vrm', source: 'genshin', avatar: '🪨' },
  { name: 'Zhongli2', filename: 'Zhongli2.vrm', source: 'genshin', avatar: '🪨' }
];

export default modelList;
